name: check updates
on:
  push:
    branches:
      - master
      - development
      - feature/*
jobs:
  execute-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Npm install
      run: npm i

    - name: check updates
      id: check_updates
      uses: ./

    - run: echo "${{ steps.check_updates.outputs.has_update }}"
    - run: echo "${{ steps.check_updates.outputs.formatted_as_json }}"
    - run: echo "${{ steps.check_updates.outputs.formatted_as_columns }}"

